// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package dto

// Email defines model for Email.
type Email struct {
	// Email valid email
	Email *string `json:"email,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// LoginCredentials defines model for LoginCredentials.
type LoginCredentials struct {
	// Email User's email address
	Email string `json:"email"`

	// Phone User's phone number
	Phone string `json:"phone"`
}

// OTP defines model for OTP.
type OTP struct {
	// OtpCode Generated OTP
	OtpCode *string `json:"otp_code,omitempty"`
}

// RegistrationResponse defines model for RegistrationResponse.
type RegistrationResponse struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// ResetCredentials defines model for ResetCredentials.
type ResetCredentials struct {
	ConfirmPassword *string `json:"confirm_password,omitempty"`
	Password        *string `json:"password,omitempty"`
}

// Success defines model for Success.
type Success struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// User defines model for User.
type User struct {
	// Email valid email
	Email string `json:"email"`

	// Name name
	Name string `json:"name"`

	// Password strong password
	Password string `json:"password"`

	// PhoneNumber valid phone number
	PhoneNumber string `json:"phone number"`
}

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = User

// PostResetJSONRequestBody defines body for PostReset for application/json ContentType.
type PostResetJSONRequestBody = Email

// PostResetRequestIdChangeJSONRequestBody defines body for PostResetRequestIdChange for application/json ContentType.
type PostResetRequestIdChangeJSONRequestBody = ResetCredentials

// PostResetRequestIdVerifyJSONRequestBody defines body for PostResetRequestIdVerify for application/json ContentType.
type PostResetRequestIdVerifyJSONRequestBody = OTP
