// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package dto

const (
	BearerScopes = "Bearer.Scopes"
)

// Phone defines model for Phone.
type Phone struct {
	// Phone valid phone
	Phone *string `json:"phone,omitempty"`
}

// RefreshTokenReq defines model for RefreshTokenReq.
type RefreshTokenReq struct {
	// RefreshToken User's refresh token
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenRes defines model for RefreshTokenRes.
type RefreshTokenRes struct {
	// BearerToken New Bearer token
	BearerToken string `json:"bearer_token"`

	// RefreshToken New Refresh token
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email valid email
	Email string `json:"email"`

	// Name name
	Name string `json:"name"`

	// Password strong password
	Password string `json:"password"`

	// PhoneNumber valid phone number
	PhoneNumber string `json:"phone number"`
}

// RequestLogin defines model for RequestLogin.
type RequestLogin struct {
	// Password User's password
	Password string `json:"password"`

	// Phone User's phone number
	Phone string `json:"phone"`
}

// RequestOTP defines model for RequestOTP.
type RequestOTP struct {
	// OtpCode Generated OTP
	OtpCode string `json:"otp_code"`
}

// RequestResetCredentials defines model for RequestResetCredentials.
type RequestResetCredentials struct {
	ConfirmPassword string `json:"confirm_password"`
	Password        string `json:"password"`
}

// Response defines model for Response.
type Response struct {
	Code    *float32                `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Error   *string                 `json:"error,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

// ResponseError defines model for ResponseError.
type ResponseError struct {
	Code    *string `json:"code,omitempty"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// ResponseSuccess defines model for ResponseSuccess.
type ResponseSuccess struct {
	Code    *string `json:"code,omitempty"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// RefreshTokenJSONRequestBody defines body for RefreshToken for core/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenReq

// RegisterJSONRequestBody defines body for Register for core/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResetJSONRequestBody defines body for Reset for core/json ContentType.
type ResetJSONRequestBody = Phone

// VerifyResetOTPJSONRequestBody defines body for VerifyResetOTP for core/json ContentType.
type VerifyResetOTPJSONRequestBody = RequestOTP

// ChangePasswordJSONRequestBody defines body for ChangePassword for core/json ContentType.
type ChangePasswordJSONRequestBody = RequestResetCredentials

// VerifyPhoneJSONRequestBody defines body for VerifyPhone for core/json ContentType.
type VerifyPhoneJSONRequestBody = Phone

// VerifyVerificationOTPJSONRequestBody defines body for VerifyVerificationOTP for core/json ContentType.
type VerifyVerificationOTPJSONRequestBody = RequestOTP
