// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerScopes     = "Bearer.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BuyRequestDelivery.
const (
	BuyRequestDeliveryDollar BuyRequestDelivery = "Dollar"
	BuyRequestDeliveryKSH    BuyRequestDelivery = "KSH"
)

// Defines values for BuyRequestPayIn.
const (
	BuyRequestPayInDollar BuyRequestPayIn = "Dollar"
	BuyRequestPayInKSH    BuyRequestPayIn = "KSH"
)

// Defines values for BuyRequestYouBuy.
const (
	BuyRequestYouBuyDollar BuyRequestYouBuy = "Dollar"
	BuyRequestYouBuyKSH    BuyRequestYouBuy = "KSH"
)

// Defines values for TopUpRequestPaymentMethod.
const (
	TopUpRequestPaymentMethodDollar TopUpRequestPaymentMethod = "Dollar"
	TopUpRequestPaymentMethodKSH    TopUpRequestPaymentMethod = "KSH"
)

// AccountOverviewResponse defines model for AccountOverviewResponse.
type AccountOverviewResponse struct {
	// Balance Current account balance
	Balance        *float32                    `json:"balance,omitempty"`
	Data           *AccountOverviewResponseObj `json:"data,omitempty"`
	PaymentDetails *struct {
		// AmountPaid Amount paid in the transaction
		AmountPaid *float32 `json:"amountPaid,omitempty"`

		// RemainingBalance Remaining balance after the transaction
		RemainingBalance *float32 `json:"remainingBalance,omitempty"`
	} `json:"paymentDetails,omitempty"`

	// TransactionSummary Summary or details of the payment made
	TransactionSummary *map[string]interface{} `json:"transactionSummary,omitempty"`
}

// AccountOverviewResponseObj defines model for AccountOverviewResponseObj.
type AccountOverviewResponseObj struct {
	// Balance Current account balance
	Balance        *float32 `json:"balance,omitempty"`
	PaymentDetails *struct {
		// AmountPaid Amount paid in the transaction
		AmountPaid *float32 `json:"amountPaid,omitempty"`

		// RemainingBalance Remaining balance after the transaction
		RemainingBalance *float32 `json:"remainingBalance,omitempty"`
	} `json:"paymentDetails,omitempty"`

	// TransactionSummary Summary or details of the payment made
	TransactionSummary *struct {
		// Date Date of the transaction
		Date *openapi_types.Date `json:"date,omitempty"`

		// Description Description of the transaction
		Description *string `json:"description,omitempty"`
	} `json:"transactionSummary,omitempty"`
}

// BadOTPResponseObj defines model for BadOTPResponseObj.
type BadOTPResponseObj struct {
	Phone *string `json:"phone,omitempty"`
}

// BuyRequest defines model for BuyRequest.
type BuyRequest struct {
	Amount   *float32            `json:"amount,omitempty"`
	Delivery *BuyRequestDelivery `json:"delivery,omitempty"`
	PayIn    *BuyRequestPayIn    `json:"payIn,omitempty"`

	// YouBuy the currrency you want to buy in
	YouBuy *BuyRequestYouBuy `json:"youBuy,omitempty"`
}

// BuyRequestDelivery defines model for BuyRequest.Delivery.
type BuyRequestDelivery string

// BuyRequestPayIn defines model for BuyRequest.PayIn.
type BuyRequestPayIn string

// BuyRequestYouBuy the currrency you want to buy in
type BuyRequestYouBuy string

// BuyRequestData defines model for BuyRequestData.
type BuyRequestData struct {
	Code    *float32       `json:"code,omitempty"`
	Data    *BuyRequestObj `json:"data,omitempty"`
	Error   *string        `json:"error,omitempty"`
	Message *string        `json:"message,omitempty"`
}

// BuyRequestObj defines model for BuyRequestObj.
type BuyRequestObj struct {
	// BuyId The unique identifier of the buy request
	BuyId *int `json:"buyId,omitempty"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// Phone name
	Phone *string `json:"phone,omitempty"`
}

// LogoutResponseData defines model for LogoutResponseData.
type LogoutResponseData struct {
	Code    *float32 `json:"code,omitempty"`
	Data    *string  `json:"data,omitempty"`
	Error   *string  `json:"error,omitempty"`
	Message *string  `json:"message,omitempty"`
}

// MarketplaceOffersResponse defines model for MarketplaceOffersResponse.
type MarketplaceOffersResponse struct {
	Currencies *struct {
		// KSH Conversion rate from US Dollar to Kenyan Shilling
		KSH *float32 `json:"KSH,omitempty"`

		// USD Conversion rate from Kenyan Shilling to US Dollar
		USD *float32 `json:"USD,omitempty"`
	} `json:"currencies,omitempty"`
	Data *MarketplaceOffersResponseObj `json:"data,omitempty"`
}

// MarketplaceOffersResponseObj defines model for MarketplaceOffersResponseObj.
type MarketplaceOffersResponseObj = []struct {
	// Currency Currency code
	Currency *string `json:"currency,omitempty"`

	// Rate Exchange rate for the currency
	Rate *float32 `json:"rate,omitempty"`
}

// OTPResponseData defines model for OTPResponseData.
type OTPResponseData struct {
	Code    *float32        `json:"code,omitempty"`
	Data    *OTPResponseObj `json:"data,omitempty"`
	Error   *string         `json:"error,omitempty"`
	Message *string         `json:"message,omitempty"`
}

// OTPResponseObj defines model for OTPResponseObj.
type OTPResponseObj struct {
	TrackingUuid *string `json:"tracking_uuid,omitempty"`
}

// OTPVerificationReq defines model for OTPVerificationReq.
type OTPVerificationReq struct {
	// OtpCode Generated OTP
	OtpCode string `json:"otp_code"`
}

// OTPVerifyResponseData defines model for OTPVerifyResponseData.
type OTPVerifyResponseData struct {
	Code *float32 `json:"code,omitempty"`
	Data *struct {
		TrackingUuid *string `json:"tracking_uuid,omitempty"`
	} `json:"data,omitempty"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Phone defines model for Phone.
type Phone struct {
	// Phone valid phone
	Phone *string `json:"phone,omitempty"`
}

// PhoneVerificationResponse defines model for PhoneVerificationResponse.
type PhoneVerificationResponse struct {
	Data *struct {
		BearerToken  *string `json:"bearer_token,omitempty"`
		RefreshToken *string `json:"refresh_token,omitempty"`
	} `json:"data,omitempty"`

	// Error Error
	Error *string `json:"error,omitempty"`

	// Message Message
	Message *string `json:"message,omitempty"`

	// StatusCode Status code
	StatusCode *float32 `json:"status_code,omitempty"`
}

// RefreshTokenReq defines model for RefreshTokenReq.
type RefreshTokenReq struct {
	// RefreshToken User's refresh token
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenRes defines model for RefreshTokenRes.
type RefreshTokenRes struct {
	Data *struct {
		// BearerToken New Bearer token
		BearerToken string `json:"bearer_token"`

		// RefreshToken New Refresh token
		RefreshToken string `json:"refresh_token"`
	} `json:"data,omitempty"`

	// Error Error
	Error *string `json:"error,omitempty"`

	// Message Message
	Message *string `json:"message,omitempty"`

	// StatusCode Status code
	StatusCode *float32 `json:"status_code,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email valid email
	Email string `json:"email"`

	// Name name
	Name string `json:"name"`

	// Password strong password
	Password string `json:"password"`

	// PhoneNumber valid phone number
	PhoneNumber string `json:"phone_number"`
}

// RegisterResponseData defines model for RegisterResponseData.
type RegisterResponseData struct {
	Code *float32 `json:"code,omitempty"`
	Data *struct {
		// Email valid email
		Email string `json:"email"`

		// Name name
		Name string `json:"name"`

		// PhoneNumber valid phone number
		PhoneNumber string `json:"phone_number"`
	} `json:"data,omitempty"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// RequestLogin defines model for RequestLogin.
type RequestLogin struct {
	// Password User's password
	Password string `json:"password"`

	// Phone User's phone number
	Phone string `json:"phone"`
}

// RequestResetCredentials defines model for RequestResetCredentials.
type RequestResetCredentials struct {
	ConfirmPassword string `json:"confirm_password"`
	Password        string `json:"password"`
}

// ResendNewOTPResponse defines model for ResendNewOTPResponse.
type ResendNewOTPResponse struct {
	Data *OTPResponseObj `json:"data,omitempty"`

	// Error Error
	Error *string `json:"error,omitempty"`

	// Message Message
	Message *string `json:"message,omitempty"`

	// StatusCode Status code
	StatusCode *float32 `json:"status_code,omitempty"`
}

// Response defines model for Response.
type Response struct {
	Code    *float32                `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Error   *string                 `json:"error,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

// ResponseBadOTPRequest defines model for ResponseBadOTPRequest.
type ResponseBadOTPRequest struct {
	Code    *float32           `json:"code,omitempty"`
	Data    *BadOTPResponseObj `json:"data,omitempty"`
	Error   *string            `json:"error,omitempty"`
	Message *string            `json:"message,omitempty"`
}

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest struct {
	Code    *float32                `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Error   *string                 `json:"error,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

// ResponseServerError defines model for ResponseServerError.
type ResponseServerError struct {
	Code    *float32                `json:"code,omitempty"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Error   *string                 `json:"error,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

// TopUpRequest defines model for TopUpRequest.
type TopUpRequest struct {
	Amount        *float32                   `json:"amount,omitempty"`
	PaymentMethod *TopUpRequestPaymentMethod `json:"paymentMethod,omitempty"`
}

// TopUpRequestPaymentMethod defines model for TopUpRequest.PaymentMethod.
type TopUpRequestPaymentMethod string

// TopUpRequestData defines model for TopUpRequestData.
type TopUpRequestData struct {
	Code    *float32          `json:"code,omitempty"`
	Data    *TopUpResponseObj `json:"data,omitempty"`
	Error   *string           `json:"error,omitempty"`
	Message *string           `json:"message,omitempty"`
}

// TopUpResponseObj defines model for TopUpResponseObj.
type TopUpResponseObj struct {
	// TopUpId The unique identifier of the top-up request
	TopUpId *int `json:"topUpId,omitempty"`
}

// UserResponseData defines model for UserResponseData.
type UserResponseData struct {
	Code    *float32         `json:"code,omitempty"`
	Data    *UserResponseObj `json:"data,omitempty"`
	Error   *string          `json:"error,omitempty"`
	Message *string          `json:"message,omitempty"`
}

// UserResponseObj defines model for UserResponseObj.
type UserResponseObj struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = RequestLogin

// VerifyLoginOTPJSONRequestBody defines body for VerifyLoginOTP for application/json ContentType.
type VerifyLoginOTPJSONRequestBody = OTPVerificationReq

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenReq

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResetJSONRequestBody defines body for Reset for application/json ContentType.
type ResetJSONRequestBody = Phone

// VerifyResetOTPJSONRequestBody defines body for VerifyResetOTP for application/json ContentType.
type VerifyResetOTPJSONRequestBody = OTPVerificationReq

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = RequestResetCredentials

// VerifyPhoneJSONRequestBody defines body for VerifyPhone for application/json ContentType.
type VerifyPhoneJSONRequestBody = Phone

// VerifyVerificationOTPJSONRequestBody defines body for VerifyVerificationOTP for application/json ContentType.
type VerifyVerificationOTPJSONRequestBody = OTPVerificationReq

// PostBuyCurrencyJSONRequestBody defines body for PostBuyCurrency for application/json ContentType.
type PostBuyCurrencyJSONRequestBody = BuyRequest

// PostTopUpAccountJSONRequestBody defines body for PostTopUpAccount for application/json ContentType.
type PostTopUpAccountJSONRequestBody = TopUpRequest
