version: '3'

tasks:

  gin-types:
    cmds:
      - oapi-codegen --package=dto  --generate types ../../docs/everyshilling_openapi.yaml> internal/dto/http.gen.go
    silent: false

  gin-handlers:
    cmds:
      - oapi-codegen --package=handlers --generate gin ../../docs/everyshilling_openapi.yaml> internal/routes/handlers/handler.gen.go
    silent: false


  build:
    desc: Build the app-exchange microservice
    cmds:
      - go build -o app-exchange


    silent: false
  run:
   desc: Run the app-exchange microservice
   cmds:
     - go run main.go serve
     -
   silent: false