---
version: "3.8"
services:
  app-auth:
    image: 540828511394.dkr.ecr.us-east-1.amazonaws.com/twala:auth
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      - JWT_SECRET=myjwtsecret
      - JWT_EXPIRY=1440
      - JWT_REFRESH_EXPIRY=30
      - DB_PORT=3001
      - DB_HOST=app-db
      - OTP_PORT=3008
      - OTP_HOST=app-otp
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_USER=myredisuser
      - REDIS_PASSWORD=myredispassword
      - PORT=3002
    ports:
      - "3002:3002"
    secrets:
      - ecr-login
  postgres-db:
    image: postgres:9.4
    deploy:
      placement:
        constraints:
          - node.role == worker
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=everyshillings
      - POSTGRES_TIMEZONE=UTC
    ports:
      - "5432:5432"
    secrets:
      - ecr-login
  redis-db:
    image: redis
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - "6379:6379"
    secrets:
      - ecr-login
  app-db:
    image: 540828511394.dkr.ecr.us-east-1.amazonaws.com/twala:db
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      - SERVER_PORT=3001
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=everyshillings
      - TZ=UTC
      - POSTGRES_TIMEZONE=UTC
    ports:
      - "3001:3001"
    secrets:
      - ecr-login
volumes:
  db:
    driver: local
secrets:
  ecr-login:
    external: true