version: '3'
services:

#mocking API using prism http server
  prism:
    image: stoplight/prism:4
    # command: 'mock -h 0.0.0.0 /usr/src/prism/'

    command: mock -p 4010 --host 0.0.0.0 everyshilling_openapi.yaml
    ports:
      - "4010:4010"

    volumes:
      - ./docs/everyshilling_openapi.yaml:/usr/src/prism/packages/cli/everyshilling_openapi.yaml



#backend services for both python and go
  app-auth:
    container_name: app-auth
    build:
      context: services/auth
      dockerfile: ${ENVIRONMENT}.Dockerfile
    env_file:
      - .env
    restart: always
    environment:
      - PORT=${AUTH_GRPC_PORT}
    healthcheck:
      test: ping -c3 app-auth:${AUTH_GRPC_PORT}
      interval: 10s
      retries: 10



# #postgres database
#   db:
#     image: postgres
#     environment:
#       - "POSTGRES_USER=${DATABASE_USER}"
#       - "POSTGRES_DB=${DATABASE_NAME}"
#       - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
#       - "POSTGRES_HOST=${DATABASE_HOST}"
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"


