version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      DOCKERHUB_REPO: <DOCKERHUB_REPO>
      DOCKERHUB_USERNAME: <DOCKERHUB_USERNAME>
      DOCKERHUB_PASSWORD: <DOCKERHUB_PASSWORD>
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - run:
          name: Build and push images
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            make -f Makefile run-dev
            docker tag everyshilling_backend $DOCKERHUB_REPO
            docker push $DOCKERHUB_REPO
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
