version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Images
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            make run-dev
            docker tag everyshilling-backend:latest $DOCKERHUB_USERNAME/everyshilling-backend:latest
            docker push $DOCKERHUB_USERNAME/everyshilling-backend:latest
