version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install make
      - run:
          name: Build and push Docker image
          command: |
            make run-dev
            docker tag <image-name>:latest <dockerhub-username>/<image-name>:latest
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push <dockerhub-username>/<image-name>:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
