# config.file: ./Monitoring/prometheus.yml

# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# rule_files:
#   # - "first.rules"
#   # - "second.rules"

# scrape_configs:
#   - job_name: prometheus
#     static_configs:
#       - targets: ['localhost:9090']

#   - job_name: app-auth
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['app-auth:3002']

#   - job_name: app-db
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['app-db:3001']

#   - job_name: app-otp
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['app-otp:3008']
