# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).


  external_labels:
      monitor: 'everyshilling'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'cadvisor'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

#     static_configs:
#          - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']

# config.file: ./Monitoring/prometheus.yml

# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# rule_files:
#   # - "first.rules"
#   # - "second.rules"

# scrape_configs:
#   - job_name: prometheus
#     static_configs:
#       - targets: ['localhost:9090']

  - job_name: app-auth
    scrape_interval: 5s
    static_configs:
      - targets: ['app-auth:3002']

  - job_name: app-db
    scrape_interval: 5s
    static_configs:
      - targets: ['app-db:3001']

  - job_name: app-otp
    scrape_interval: 5s
    static_configs:
      - targets: ['app-otp:3008']
