apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-auth
  template:
    metadata:
      labels:
        app: app-auth
    spec:
      containers:
      - name: app-auth
        image: app-auth:latest
        ports:
        - containerPort: 3002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-otp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-otp
  template:
    metadata:
      labels:
        app: app-otp
    spec:
      containers:
      - name: app-otp
        image: app-otp:latest
        ports:
        - containerPort: 3008


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-otp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
      - name: app-db
        image: app-db:latest
        ports:
        - containerPort: 3001


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-otp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        ports:
        - containerPort: 5432
