apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-deployment
  labels:
    app: auth

spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: go-app-auth
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
