apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserver
  namespace: grpcserver
spec:
  selector:
    matchLabels:
      app: grpcserver
  replicas: 1
  template:
    metadata:
      labels:
        app: grpcserver
    spec:
      containers:

      - name: grpc-demo
        image: accountid.dkr.ecr.us-east-1.amazonaws.com/app-auth:latest   #<------- Change to the URI that the Docker image is pushed to
        imagePullPolicy: Always

        ports:
        - name: grpc-api
          containerPort: 9000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always