openapi: 3.0.0
info:
  title: Login API Endpoint
  version: 2023-03-08
  description: API to generate OTP and validate login using YAML.
contact:
    name: Every-Shilling 
    email: developers@appslab.co.ke
    url: http://appslab.co.ke/


servers:

- url:
  description: 'Mock Server'

- url:
  description: 'Staging'

- url:
  description: 'Production'


paths:

# login endpoint 
# Registration endpoint 
# forget password
# reset password
   /reset/{request-id}/verify:
    post:
      tags: [Password Reset]
      summary: "Verify OTP"
      description: "Once a user has sent their email, they receive an OTP code for verifying if indeed they are the owners of the account"
      parameters:
        - name: request-id
          description: "Password reset request UUID"
          required: true
          in: path
          schema:
            type: string
            example: "f8e33eb4-d6da-4c2e-9857-8294b178e361"
      requestBody:
        description: "The 6 Digit OTP code sent to the user's email"
        content:
          application/json:
            schema:
              properties:
                otp_code:
                  type: string
                  example: "123456"

      responses:
        200:
          description: "Verificatopn successful"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "OTP verification Success"
                  code:
                    type: string
                    example: "OTP_SUCCESS"
        401:
          description: "Verification failed"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "OTP verification failed, invalid OTP"
                  code:
                    type: string
                    example: "OTP_INVALID_CODE"

        404:
          description: "Request ID not found/valid"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Invalid request ID"
                  code:
                    type: string
                    example: "OTP_INVALID_REQUEST"

   /reset/{request-id}/change:
    post:
      tags: [Password Reset]
      summary: "Change Password"
      description: "On successful OTP verification, user sends a new password"
      parameters:
        - name: request-id
          description: "Password reset request UUID"
          required: true
          in: path
          schema:
            type: string
            example: "f8e33eb4-d6da-4c2e-9857-8294b178e361"
      requestBody:
        description: "The user's new passwords"
        content:
          application/json:
            schema:
              properties:
                password:
                  type: string
                  example: "BlackApple78"
                confirm_password:
                  type: string
                  example: "BlackApple78"


      responses:
        200:
          description: "Reset successful"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Password Reset Success"
                  code:
                    type: string
                    example: "RESET_SUCCESS"
        400:
          description: "Password mismatch"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Passwords do not match"
                  code:
                    type: string
                    example: "RESET_PASSWORD_MISMATCH"

        401:
          description: "Verification failed"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "OTP verification pending"
                  code:
                    type: string
                    example: "RESET_PENDING_OTP"

        404:
          description: "Request ID not found/valid"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Invalid request ID"
                  code:
                    type: string
                    example: "RESET_INVALID_REQUEST"


