openapi: 3.0.3
info:
  title: Every shillings Auth OpenAPI endpoint
  description: Every Shilling
  version: 2022-04-01
  termsOfService: https://everyshilling.ke/terms
  contact:
    name: Everyshilling
    email: everyshilling@co.ke
    url: https://everyshilling.ke
servers:
  - url: 'http://127.0.0.1:4010'
    description: 'Mock server'
  - url: 'http://localhost:8080/v1'
    description: 'Local'
  - url: ''
    description: 'Staging'
  - url: ''
    description: 'Production'


paths:

# login endpoint 
# Registration endpoint 
# forget password
# reset password