version: 3

tasks:
  types:
    cmds:
      - oapi-codegen --package=dto  --generate types everyshilling_openapi.yaml> ../services/app-auth/internal/dto/http_dto.go
    silent: false

  gin:
    cmds:
      - oapi-codegen --package=handlers --generate gin everyshilling_openapi.yaml> ../services/app-auth/internal/routes/handlers/handler.go
    silent: false