name: Microservices CI

on:
  push:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Go microservice
      run: go build -o go-microservice ./go

    - name: Test Go microservice
      run: go test ./go/...

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Test Python microservice
      run: pytest ./python
