name: Mockserver Autodeployment
on:
  push:
    branches:
      - oyamo-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker version

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AWS SSM Send Command
        uses: elsiedev/aws-ssm-send-command-action@develop
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1
          instance-id:  ${{ secrets.INSTANCE_ID  }}
      - name: Deployment script
        run: |            
          cd /home/ubuntu/backend-everyshilling && /bin/sh ./deploy.sh
