---
name: CI/CD Everyshilling
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build -t docs -f docs/Dockerfile docs/
      - name: Build the application
        run: sudo make run-dev

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}
        run: >
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            #EC2 to start the deployment .
            cd /home/ubuntu/everyshilling &&
            git checkout develop &&
            git fetch --all &&
            git reset --hard origain/main &&
            git pull origin develop &&
            make run-dev
