name: CI/CD Everyshilling

on:
  push:
    branches: [ develop ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: self-hosted

    steps:
    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y make
          sudo apt-get -y install docker-compose
          
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: sudo make run-dev
   
 
